// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxtcLI2_9M0c-KXjv99UMzIlNBU6URd_A',
    appId: '1:490569634226:web:e94d627e41c07e02d3d4ab',
    messagingSenderId: '490569634226',
    projectId: 'week5-15671',
    authDomain: 'week5-15671.firebaseapp.com',
    storageBucket: 'week5-15671.firebasestorage.app',
    measurementId: 'G-PW01306987',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3t_--y57StASszp3ASQHxpc7IxQ6x0zc',
    appId: '1:490569634226:android:37e28e4b492d8b6cd3d4ab',
    messagingSenderId: '490569634226',
    projectId: 'week5-15671',
    storageBucket: 'week5-15671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRp0eToDVtKw4kJ3LsZMFziIen3aws3SE',
    appId: '1:490569634226:ios:1ad5074ad8ffc308d3d4ab',
    messagingSenderId: '490569634226',
    projectId: 'week5-15671',
    storageBucket: 'week5-15671.firebasestorage.app',
    iosBundleId: 'com.example.tutorial13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxtcLI2_9M0c-KXjv99UMzIlNBU6URd_A',
    appId: '1:490569634226:web:a098afa4d9cb9555d3d4ab',
    messagingSenderId: '490569634226',
    projectId: 'week5-15671',
    authDomain: 'week5-15671.firebaseapp.com',
    storageBucket: 'week5-15671.firebasestorage.app',
    measurementId: 'G-DX046YP5CG',
  );
}
